# Splines

```{python}
#| echo: false
import numpy as np
import numpy.polynomial.polynomial as poly
import matplotlib.pyplot as plt
```

Polynomial interpolation attempts to find a global model function. However, high-degree polynomials are generally not suitable for interpolating many points. A different approach is taken by splines, which use multiple low-degree polynomials to interpolate many points. The polynomials typically have degrees between one and three.

## Definition

For $n+1$ data points $(x_i, y_i)$, a spline function $s_k$, here a polynomial spline, can be defined as follows:

* It is assumed that the data points are sorted, i.e., $x_0 < x_1 < \cdots < x_n$.
* For each $i = 0 \dots n-1$, $s_k$ is a polynomial of degree $k$ on the interval $\left[x_i , x_{i+1}\right]$.
* $s_k$ is $(k-1)$-times continuously differentiable on $\left[x_0 , x_n \right]$.

Examples:

* $k = 1$: piecewise linear spline
* $k = 3$: cubic polynomial splines (B-splines)

## Cubic Splines

The cubic polynomial splines $s_3$ ($k = 3$) commonly used in practice have the following properties:

* $s_3|\left[x_i,x_{i+1}\right] = \beta_0 + \beta_1 x + \beta_2 x^2 + \beta_3 x^3$
* $s_3$ is twice continuously differentiable on $\left[x_0,x_n\right]$, especially at the support points $x_i$ of the data points.

The coefficients $\beta_i$ are determined as follows:

* From the $n + 1$ data points, there are $n$ intervals, i.e., with four coefficients each, there are a total of $4n$ coefficients.
* Exact representation of the data points ($n + 1$ equations), i.e., $s_3(x_i) = y_i$.
* Smoothness conditions at the internal data points ($i = 1 \dots n-1$), each providing ($n - 1$ equations):
$$
s_3'(x_i)_- = s_3'(x_i)_+
$$
$$
s_3''(x_i)_- = s_3''(x_i)_+
$$
$$
s_3'''(x_i)_- = s_3'''(x_i)_+
$$

* This gives $4n - 2$ equations for $4n$ coefficients.

To determine the two remaining equations, boundary or endpoint conditions are required. The most common conditions are:

* Natural splines: the curvature at the boundary vanishes, i.e.:
$$
s_3''(x_0) = s_3''(x_n) = 0
$$

* Periodic splines: the slope and curvature are equal at both boundaries:
$$
s_3'(x_0) = s_3'(x_n)
$$
$$
s_3''(x_0) = s_3''(x_n)
$$

* Hermite splines: the slopes at the boundaries are explicitly specified (here by $u$ and $v$):
$$
s_3'(x_0) = u
$$
$$
s_3'(x_n) = v
$$

## Application

The following shows two examples, $s_1$ and $s_3$, for creating splines in Python.

```{python}
# Generate data points
n = 7
xi = np.linspace(0, np.pi, n)
yi = np.sin(xi)
```


For $s_1$ splines, the function `np.interp()` can be used. It performs linear interpolation between given pairs of values.
```{python}
# Range of values for visualizing the interpolation

x = np.linspace(0, np.pi, n*6)
y = np.sin(x)
```

```{python}
# Interpolation
y_s1 = np.interp(x, xi, yi)
```

```{python}
#| fig-alt: "Visualization of the generating function as an inverted U and its approximation using 6 lines."

plt.plot(x, y, alpha=0.3, color='C2', lw=5,
label='Generating Function')
plt.plot(x, y_s1, color='C0', label='Interpolation')
plt.scatter(x, y_s1, s=3, zorder=3, color='C0')
plt.scatter(xi, yi, color='C1', label='Data Points')

plt.xlabel('x')
plt.ylabel('y')
plt.legend();

plt.show()
```

&nbsp;

The $s_3$ splines can be computed using functions from the scipy module. First, the coefficients are determined (`scipy.interpolate.splrep`), which then allow the desired evaluation using the function `scipy.interpolate.splev`.
```{python}
import scipy.interpolate as si
```


```{python}
s3 = si.splrep(xi, yi)
y_s3 = si.splev(x, s3)
```

```{python}
#| fig-alt: "Visualization of the generating function in the shape of an inverted U and its precise approximation using cubic polynomial splines."

plt.plot(x, y, alpha=0.3, color='C2', lw=5,
label='Generating Function')
plt.plot(x, y_s3, color='C0', label='Interpolation')
plt.scatter(x, y_s3, s=3, zorder=3, color='C0')
plt.scatter(xi, yi, color='C1', label='Data Points')

plt.xlabel('x')
plt.ylabel('y')
plt.legend();

plt.show()
```